export const CH = {
  todayGet: 'today:get',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  consentGrant: 'consent:grant',
  profileGet: 'profile:get',
  profileSave: 'profile:save',
  trackingStatus: 'tracking:status',
  trackingSet: 'tracking:set',
  eventsUpdate: 'events:update',
  privacyGet: 'privacy:get',
  privacySetExclusions: 'privacy:setExclusions',
  privacyExport: 'privacy:export',
  privacyDeleteActivity: 'privacy:deleteActivity',
  privacyOpenLanguageSettings: 'privacy:openLanguageSettings',
  modelsGet: 'models:get',
  modelsRedownload: 'models:redownload',
  modelsDelete: 'models:delete',
  modelsRetryLabelling: 'models:retryLabelling'
} as const;
