export const CH = {
  trackingGetStatus: 'tracking:getStatus',
  trackingPause: 'tracking:pause',
  trackingResume: 'tracking:resume',
  summaryGetDay: 'summary:getDay',
  summaryGetDays: 'summary:getAvailableDays',
  summaryGenerateAi: 'summary:generateAi',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsSetApiKey: 'settings:setApiKey',
  dataClearAll: 'data:clearAll',
  eventsUpdate: 'events:update',
  cloudGetStatus: 'cloud:getStatus',
  cloudSignIn: 'cloud:signIn',
  cloudSignOut: 'cloud:signOut',
  cloudSetEnabled: 'cloud:setEnabled',
  cloudSyncNow: 'cloud:syncNow',
} as const;
